name: 'Install dependencies and test'

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/tests.yml"
#    types:
#      - opened
#      - synchronize
#      - reopened
#      - draft
#      - ready_for_review
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout data'
        uses: actions/checkout@v3

      - name: 'Install composer dependencies'
        uses: php-actions/composer@v6

