name: 'Install dependencies and test'

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/**"
    branches:
      - main
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/**"
    types:
      - opened
      - synchronize
      - reopened
      - draft
      - ready_for_review
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Cache vendor folder'
        uses: actions/cache@v3
        with:
          path: /vendor
          key: ${{ github.sha }}

      - name: 'Composer install'
        run: docker run --rm -v $(pwd):/app composer install

      - name: Retrieve cached vendor folder
        uses: actions/cache@v3
        with:
          path: /vendor
          key: ${{ github.sha }}
