name: 'Install dependencies and test'

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/tests.yml"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout data'
        uses: actions/checkout@v3

      - name: 'Cache composer dependencies'
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: 'Install composer dependencies'
        uses: php-actions/composer@v6

