name: 'Install dependencies and test'

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/**"
    branches:
      - main
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/**"
    types:
      - opened
      - synchronize
      - reopened
      - draft
      - ready_for_review
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Cache composer results'
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: ./composer.lock
          key: ${{ github.sha }}-composer

      - name: 'Composer install'
        if: steps.cache-composer.outputs.cache-hit != 'true'
        run: docker run --rm -v $(pwd):/app composer install
