name: 'Install dependencies and test'

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/**"
    branches:
      - main
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/**"
    types:
      - opened
      - synchronize
      - reopened
      - draft
      - ready_for_review
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Cache Composer dependencies'
        id: cache-vendor
        uses: actions/cache@v3
        with:
          path: /vendor
#          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          key: ${{ runner.os }}-vendor

      - name: 'Install composer dependencies'
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: docker run --rm -v $(pwd):/app composer install
#        uses: php-actions/composer@v6

#      - name: 'Run PHPUnit tests'
#        uses: php-actions/phpunit@v3
