name: 'Install dependencies and test'

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/build.yml"
    branches:
      - main
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/build.yml"
    types:
      - opened
      - synchronize
      - reopened
      - draft
      - ready_for_review
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

#      - name: 'Cache Composer dependencies'
#        uses: actions/cache@v3
#        with:
#          path: /tmp/composer-cache
#          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
#
#      - name: 'Install composer dependencies'
#        uses: php-actions/composer@v6
#
#      - name: 'Run PHPUnit tests'
#        uses: php-actions/phpunit@v3
