name: 'Build new based on the PR changes'

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/build.yml"
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Create release with increment'
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          auto_increment_type: 'patch'
          tag_schema: 'semantic'
          prerelease: true
