name: 'Build new release from changes'

on:
  pull_request:
    branches:
      - main
#    types:
#      - closed

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: Get latest release
        id: latest_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest: true

#      - name: 'Create release'
#        run: echo ${{ github.event.release.name }}
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: 'v2023.2.2'
#          release_name: 'v2023.2.2'
#          draft: false
#          prerelease: true
