name: Tests

on:
  pull_requests:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - name: Install dependencies
        uses: docker://composer:latest
        with:
          args: install
