name: Tests

on:
  push:
    branches:
      - main
  pull_request:
#    paths:
#      - "src/**"
#      - ".github/workflows/tests.yml"
    types:
      - opened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout data
        uses: actions/checkout@v3

      - name: Install dependencies
        run: docker run --rm -v $(pwd):/app composer install

      - name: Tests
        run: docker run --rm -v $(pwd):/app -w /app php:8.2-cli vendor/bin/phpunit

