name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/tests.yml"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

