name: Tests

on:
  push:
    paths:
      - "**"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Install dependencies
#        run: docker run --rm -v $(pwd):/app composer install
        run: ls -l
